# Generated by Django 4.0 on 2022-03-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recepient',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
