# Generated by Django 4.0 on 2022-03-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_city_profile_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(choices=[('Bagmati', 'Bagmati')], max_length=20, null=True),
        ),
    ]
