# Generated by Django 4.0 on 2021-12-24 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_title', models.CharField(max_length=200, null=True)),
                ('vehicle_type', models.CharField(choices=[('C', 'Car'), ('M', 'Motrobike'), ('B', 'Bicycle'), ('S', 'Scooter'), ('O', 'Other')], max_length=1, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('distance_travelled', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('available_from', models.DateField(null=True)),
                ('available_till', models.DateField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('featured_image', models.ImageField(blank=True, default='ads/ad-default.jpg', null=True, upload_to='ads/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('make', models.CharField(max_length=100, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
