# Generated by Django 4.0 on 2021-12-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='ad',
            name='vehicle_make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ads.vehiclemake'),
        ),
    ]
