# Generated by Django 4.0 on 2021-12-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
