# Generated by Django 4.0 on 2021-12-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created']},
        ),
    ]
