# Generated by Django 4.0 on 2021-12-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_image'),
        ('ads', '0003_ad_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
