# Generated by Django 4.0.3 on 2022-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_adreview_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='available_till',
        ),
        migrations.AddField(
            model_name='ad',
            name='engine_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Engine capacity in CC'),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
