# Generated by Django 4.0 on 2021-12-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, default='images/requests/request-default.jpg', null=True, upload_to='images/requests')),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
