# Generated by Django 4.0 on 2022-03-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='vehicle_type',
            field=models.CharField(choices=[('C', 'Car'), ('M', 'Motrobike'), ('B', 'Bicycle'), ('S', 'Scooter'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
