# Generated by Django 4.0 on 2021-12-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_created_alter_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, default='requests/request-default.jpg', null=True, upload_to='requests'),
        ),
    ]
