# Generated by Django 4.0 on 2021-12-23 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('type', models.CharField(choices=[('C', 'Car'), ('M', 'Motrobike'), ('B', 'Bicycle'), ('O', 'Other')], max_length=1, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('distance_travelled', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, default='images/vehicles/vehicle-default.jpg', null=True, upload_to='images/vehicles')),
            ],
        ),
    ]
