# Generated by Django 4.0 on 2021-12-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclemake_vehicle_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, default='vehicles/vehicle-default.jpg', null=True, upload_to='vehicles'),
        ),
    ]
